name: CI/CD Microservice Build Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-ship:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Application Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Backend Image
      working-directory: ./backend # 👈 Declares the working directory cleanly
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/microservice-upvote-backend:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservice-upvote-backend:${{ github.sha }}

    - name: Build and Push Frontend Image
      working-directory: ./frontend # 👈 Declares the working directory cleanly
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/microservice-upvote-frontend:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservice-upvote-frontend:${{ github.sha }}

    - name: Commit New Tags to Infrastructure Repo
      env:
        GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions Automation"
        
        git clone https://${{ secrets.GITOPS_TOKEN }}@github.com/${{ github.repository_owner }}/engagement-infra.git
        cd engagement-infra/k8s
        
        sed -i 's|image: .*microservice-upvote-backend:.*|image: '${{ secrets.DOCKERHUB_USERNAME }}'/microservice-upvote-backend:'${{ github.sha }}'|g' platform-tier.yaml
        sed -i 's|image: .*microservice-upvote-frontend:.*|image: '${{ secrets.DOCKERHUB_USERNAME }}'/microservice-upvote-frontend:'${{ github.sha }}'|g' platform-tier.yaml
        
        git add platform-tier.yaml
        git commit -m "automation: dynamically upgraded microservice-upvote-app containers to hash version ${{ github.sha }}"
        git push origin main